name: email-starter
version: 1.0.0
description: A boilerplate for building responsive HTML emails.
scripts:
  serve: gulp serve
  build: gulp build
  move: gulp move
repository:
  type: git
  url: 'git+https://github.com/Shyam-Chen/Email-Starter.git'
keywords: ['MJML', 'YAML', 'Nunjucks', 'Gulp']
author: Shyam Chen
license: MIT
bugs:
  url: 'https://github.com/Shyam-Chen/Email-Starter/issues'
homepage: 'https://github.com/Shyam-Chen/Email-Starter#readme'
dependencies:
  browser-sync: ^2.26.13
  gulp: ^4.0.2
  gulp-data: ^1.3.1
  gulp-if: ^3.0.0
  gulp-mjml: ^4.0.2
  gulp-nunjucks: ^5.1.0
  gulp-rename: ^2.0.0
  js-yaml: ^4.0.0
  js-yaml-import: ^1.0.3
  minimist: ^1.2.5
  mjml: ^4.8.1
  nodemailer: ^6.4.17
  nunjucks: ^3.2.2
  rimraf: ^3.0.2
